title: 新成
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://JunFuXu.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: 主页
   url: https://junfuxu.github.io/index.html
   target: _self
 - title: GitHub
   url: https://github.com/JunFuXu
   target: _blank
 - title: 简历
   url: https://junfuxu.github.io/resume
   target: _blank
 - title: 关于
   url: https://junfuxu.github.io/about
   target: _self

social:
   github: JunFuXu
   twitter: JunFuXu
   facebook: JunFuXu
   email: xujunfu@shu.edu.cn
