title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://JunFuXu.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: JunFuXu
   twitter: JunFuXu
   facebook: JunFuXu
   email: xujunfu@shu.edu.cn

google_analytics: "UA-58263416-1"
